In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## Keras Basics

In [ ]:
import numpy as np
from numpy import genfromtxt

In [ ]:
data = genfromtxt('/content/drive/MyDrive/Colab Notebooks/ComputerVision/DATA/bank_note_data.txt', delimiter=',')

In [ ]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [ ]:
labels = data[:,4]

In [ ]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [ ]:
features = data[:,0:4]

In [ ]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [ ]:
X = features
y = labels

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [ ]:
print("Lengths of: ")
print("X: " + str(len(X)))
print("X train: " + str(len(X_train)))
print("X_test: " + str(len(X_test)))

Lengths of: 
X: 1372
X train: 919
X_test: 453


In [ ]:
X_test

array([[ 1.5691  ,  6.3465  , -0.1828  , -2.4099  ],
       [-0.27802 ,  8.1881  , -3.1338  , -2.5276  ],
       [ 0.051979,  7.0521  , -2.0541  , -3.1508  ],
       ...,
       [ 3.5127  ,  2.9073  ,  1.0579  ,  0.40774 ],
       [ 5.504   , 10.3671  , -4.413   , -4.0211  ],
       [-0.2062  ,  9.2207  , -3.7044  , -6.8103  ]])

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaler_object = MinMaxScaler()

In [ ]:
scaler_object.fit(X_train)

MinMaxScaler()

In [ ]:
MinMaxScaler(copy=True, feature_range=(0,1))

MinMaxScaler()

In [ ]:
scaled_X_train = scaler_object.transform(X_train)

In [ ]:
scaled_X_test = scaler_object.transform(X_test)

In [ ]:
scaled_X_train.max()

np.float64(1.0000000000000002)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()

model.add(Dense(4,input_dim=4,activation='relu'))

model.add(Dense(8,activation='relu'))

model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
29/29 - 3s - 108ms/step - accuracy: 0.5713 - loss: 0.6853
Epoch 2/50
29/29 - 0s - 15ms/step - accuracy: 0.6616 - loss: 0.6729
Epoch 3/50
29/29 - 0s - 3ms/step - accuracy: 0.7291 - loss: 0.6595
Epoch 4/50
29/29 - 0s - 3ms/step - accuracy: 0.7334 - loss: 0.6454
Epoch 5/50
29/29 - 0s - 3ms/step - accuracy: 0.7399 - loss: 0.6309
Epoch 6/50
29/29 - 0s - 3ms/step - accuracy: 0.7476 - loss: 0.6150
Epoch 7/50
29/29 - 0s - 4ms/step - accuracy: 0.7497 - loss: 0.5978
Epoch 8/50
29/29 - 0s - 4ms/step - accuracy: 0.7606 - loss: 0.5806
Epoch 9/50
29/29 - 0s - 3ms/step - accuracy: 0.7650 - loss: 0.5642
Epoch 10/50
29/29 - 0s - 3ms/step - accuracy: 0.7758 - loss: 0.5469
Epoch 11/50
29/29 - 0s - 3ms/step - accuracy: 0.7791 - loss: 0.5304
Epoch 12/50
29/29 - 0s - 3ms/step - accuracy: 0.7943 - loss: 0.5143
Epoch 13/50
29/29 - 0s - 3ms/step - accuracy: 0.8030 - loss: 0.4992
Epoch 14/50
29/29 - 0s - 3ms/step - accuracy: 0.8052 - loss: 0.4843
Epoch 15/50
29/29 - 0s - 3ms/step - accuracy: 0.8118 -

In [ ]:
scaled_X_test

array([[0.62098955, 0.75284662, 0.21900753, 0.5730998 ],
       [0.48778602, 0.82175665, 0.09174727, 0.56211079],
       [0.51158363, 0.77924916, 0.13830875, 0.50392598],
       ...,
       [0.76115065, 0.62415668, 0.27251204, 0.83616757],
       [0.9047516 , 0.90329171, 0.03658247, 0.42267079],
       [0.49296526, 0.86039507, 0.06714046, 0.1622583 ]])

In [ ]:
np.argmax(model.predict(scaled_X_test), axis=1)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [ ]:
# model.predict(scaled_X_test)

In [ ]:
model.metrics_names

['loss', 'compile_metrics']

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report

In [ ]:
predictions = np.argmax(model.predict(X_test), axis=1)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step


In [ ]:
confusion_matrix(y_test, predictions)

array([[257,   0],
       [196,   0]])

In [ ]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         0.0       0.57      1.00      0.72       257
         1.0       0.00      0.00      0.00       196

    accuracy                           0.57       453
   macro avg       0.28      0.50      0.36       453
weighted avg       0.32      0.57      0.41       453



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
